using Xunit;

namespace LatexConverter.Tests
{
    public class ConvertToHumanFriendlyTextTests
    {
        private readonly LaTexConverter _converter = new LaTexConverter();

        [Theory]
        [InlineData(@"\textrm{k}", "k")]
        [InlineData(@"F_\textrm{k}", "Fₖ")]
        [InlineData(@"43^\circ", "43°")]
        [InlineData(@"\alpha", "α")]
        [InlineData(@"\sqrt{x}", "√x")]
        [InlineData(@"\frac{1}{2}", "1 / 2")]
        [InlineData(@"a^{b+c}", "aᵇ⁺ᶜ")]
        [InlineData(@"x^{10}", "x¹⁰")]
        [InlineData(@"\vec{F}", "F⃗")]
        [InlineData(@"\hat{x}", "x̂")]
        [InlineData(@"\mathcal{E}_1", "ℰ₁")]
        [InlineData(@"\mathbb{R}", "ℝ")]
        [InlineData(@"\text{hello}", "hello")]
        [InlineData(@"\mathrm{N}", "N")]
        [InlineData(@"\vec{v}_0", "v⃗₀")]
        [InlineData(@"a^{b^{c}}", "a^(bᶜ)")]
        [InlineData(@"\frac{\sqrt{a^2+b^2}}{2}", "√(a²+b²) / 2")]
        [InlineData(@"\sum_{i=1}^{n} i^2", "∑ᵢ₌₁ⁿ i²")]
        [InlineData(@"\int_{0}^{\infty} e^{-x} dx", "∫₀^(∞) e⁻ˣ dx")]
        [InlineData(@"\forall x \in \mathbb{R}", "∀ x ∈ ℝ")]
        [InlineData(@"\bigg( \frac{a}{b} \bigg)", "a / b")]
        [InlineData(@"90^\circ", "90°")]
        [InlineData(@"\(x_f\)", "x_f")]
        [InlineData(@"\(x_i = 0\)", "xᵢ = 0")]
        [InlineData(@"\(k = 52\;\mathrm{N}/\mathrm{m}\).", "k = 52 N/m.")]
        [InlineData(@"\(v\)", "v")]
        [InlineData("a\nb", "a\nb")]
        [InlineData("E = mc^2", "E = mc²")]
        [InlineData("4.0 \\times 10^{-4}", "4.0 × 10⁻⁴")]
        [InlineData("sin^(-1)", "sin⁻¹")]
        [InlineData("cos^(-1)", "cos⁻¹")]
        [InlineData("tan^(-1)", "tan⁻¹")]
        [InlineData("sqrt(x)", "√x")]
        [InlineData("A small segment of the wire is marked in blue as \"d-x.\"", "A small segment of the wire is marked in blue as \"d-x.\"")]
        [InlineData("An x-y coordinate system is shown in the top right", "An x-y coordinate system is shown in the top right")]
        [InlineData("rod: dE_x = -k * lambda * x * dx / (a^2 + x^2)^(3/2).", "rod: dEₓ = -k * λ * x * dx / (a² + x²)^(3/2).")]
        [InlineData("V(r) = (q / (4 * \\pi * \\epsilon_0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).", "V(r) = (q / (4 * π * ε₀ * a₀)) * e^(-2 * r / a₀) * (1 + a₀/r).")]
        [InlineData(
            "sin^(-1) [ (lambda / (d * pi)) * cos^(-1) (sqrt(I / I_0)) ]",
            "sin⁻¹[(λ / (d * π)) * cos⁻¹(√(I / I₀))]")]
        [InlineData("the quantity (x/2 squared plus l squared) raised to the 3/2 power", "the quantity (x/2 squared plus l squared) raised to the 3/2 power")]
        [InlineData("y_ob to a", "y_ob to a")]
        [InlineData(@"\mu_k", "μₖ")]
        [InlineData("H_2O", "H₂O")]
        [InlineData("x_1", "x₁")]
        [InlineData("lambda_1", "λ₁")]
        [InlineData("lambda_1 + lambda_2 = 1", "λ₁ + λ₂ = 1")]
        [InlineData("sqrt(omega_1 / omega_2)", "√(ω₁ / ω₂)")]
        [InlineData("alpha + beta", "α + β")]
        [InlineData("Delta - gamma", "Δ - γ")]
        [InlineData("alpha^2 + beta^2 = gamma^2", "α² + β² = γ²")]
        //[InlineData("sin(theta) * cos(phi)", "sin(θ) * cos(φ)")]
        [InlineData("pi * r^2", "π * r²")]
        [InlineData("kappa", "κ")]
        [InlineData("+q", "+q")]
        [InlineData("a+b", "a+b")]
        [InlineData("a - b", "a - b")]
        [InlineData("a=b", "a=b")]
        [InlineData("F_{net} = m \\cdot a", "Fₙₑₜ = m · a")]
        [InlineData("\\frac{\\alpha}{\\beta}", "α / β")]
        [InlineData("\\sqrt{a^2 + b^2}", "√(a² + b²)")]
        [InlineData("sqrt(a^2 + b^2)", "√(a² + b²)")]
        [InlineData("\\vec{F}_i", "F⃗ᵢ")]
        [InlineData(@"a \pm b", "a ± b")]
        [InlineData(@"a \neq b", "a ≠ b")]
        [InlineData(@"a \geq b", "a ≥ b")]
        [InlineData(@"\forall x", "∀ x")]
        [InlineData(@"\exists y", "∃ y")]
        [InlineData(@"z \in S", "z ∈ S")]
        [InlineData(@"\nabla f", "∇ f")]
        [InlineData(@"\partial f", "∂ f")]
        [InlineData(@"a \mp b", "a ∓ b")]
        [InlineData(@"a \equiv b", "a ≡ b")]
        [InlineData(@"\int_a^b f(x) dx", "∫ₐᵇ f(x) dx")]
        // [InlineData(@"\lim_{x \to \infty} f(x)", "lim_{x→∞} f(x)")]
        [InlineData(@"\lim_{x \to \infty} f(x)", "lim (x→∞) f(x)")]
        [InlineData(@"\begin{pmatrix} a & b \\ c & d \end{pmatrix}", "(a b)\n(c d)")]
        [InlineData(@"\sin(x)", "sin(x)")]
        [InlineData(@"\cos(x)", "cos(x)")]
        [InlineData(@"\tan(x)", "tan(x)")]
        [InlineData(@"\log(x)", "log(x)")]
        [InlineData(@"\ln(x)", "ln(x)")]
        [InlineData(@"\exp(x)", "eˣ")]
        [InlineData(@"\det(A)", "det(A)")]
        [InlineData(@"\binom{n}{k}", "(n choose k)")]
        [InlineData(@"\cup", "∪")]
        [InlineData(@"\cap", "∩")]
        [InlineData(@"\subset", "⊂")]
        [InlineData(@"\supset", "⊃")]
        [InlineData(@"\neg A", "¬A")]
        [InlineData(@"A \land B", "A ∧ B")]
        [InlineData(@"A \lor B", "A ∨ B")]
        [InlineData(@"\hbar", "ħ")]
        [InlineData(@"\ell", "ℓ")]
        [InlineData(@"\otimes", "⊗")]
        [InlineData(@"\parallel", "∥")]
        [InlineData(@"\perp", "⊥")]
        [InlineData(@"\implies", "⇒")]
        [InlineData(@"\iff", "⇔")]
        [InlineData(@"\Re", "ℜ")]
        [InlineData(@"\Im", "ℑ")]
        [InlineData(@"\odot", "⊙")]
        [InlineData(@"\approx", "≈")]
        [InlineData(@"\rightarrow", "→")]
        [InlineData(@"\leftarrow", "←")]
        [InlineData(@"\uparrow", "↑")]
        [InlineData(@"\downarrow", "↓")]
        [InlineData(@"\Rightarrow", "⇒")]
        [InlineData(@"\Leftarrow", "⇐")]
        [InlineData(@"\leftrightarrow", "↔")]
        [InlineData(@"\Leftrightarrow", "⇔")]
        [InlineData(@"The result is \approx 5.", "The result is ≈ 5.")]
        [InlineData(@"This \implies that and this \iff this.", "This ⇒ that and this ⇔ this.")]
        [InlineData(@"Move \rightarrow or \leftarrow.", "Move → or ←.")]
        [InlineData(@"An \uparrow and a \downarrow.", "An ↑ and a ↓.")]
        [InlineData(@"A \Rightarrow B \Leftarrow C.", "A ⇒ B ⇐ C.")]
        [InlineData(@"A \leftrightarrow B \Leftrightarrow C.", "A ↔ B ⇔ C.")]
        [InlineData(@"The vector is \perp to the plane.", "The vector is ⊥ to the plane.")]
        [InlineData(@"The lines are \parallel.", "The lines are ∥.")]
        [InlineData(@"This is a \odot operation.", "This is a ⊙ operation.")]
        [InlineData(@"The \Re part and the \Im part.", "The ℜ part and the ℑ part.")]
        [InlineData(@"A \cup B and C \cap D", "A ∪ B and C ∩ D")]
        [InlineData(@"E \subset F and G \supset H", "E ⊂ F and G ⊃ H")]
        [InlineData(@"\neg I \land J \lor K", "¬I ∧ J ∨ K")]
        [InlineData(@"The value of \hbar is constant, as is \ell.", "The value of ħ is constant, as is ℓ.")]
        [InlineData(@"\clubsuit", "♣")]
        [InlineData(@"\diamondsuit", "♦")]
        [InlineData(@"\heartsuit", "♥")]
        [InlineData(@"\spadesuit", "♠")]
        [InlineData(@"\flat", "♭")]
        [InlineData(@"\natural", "♮")]
        [InlineData(@"\sharp", "♯")]
        [InlineData(@"\angle", "∠")]
        [InlineData(@"\measuredangle", "∡")]
        [InlineData(@"f^\prime", "f′")]
        [InlineData(@"\dots", "…")]
        [InlineData(@"\cdots", "⋯")]
        [InlineData(@"\vdots", "⋮")]
        [InlineData(@"\ddots", "⋱")]
        [InlineData(@"\blacksquare", "■")]
        [InlineData(@"\triangle", "△")]
        [InlineData(@"\triangledown", "▽")]
        [InlineData("slope until x_2.", "slope until x₂.")]
        [InlineData("and n_2. A light ray", "and n₂. A light ray")]
        [InlineData("a\r\nb", "a\r\nb")]
        [InlineData("\r\n\\alpha\r\n\\beta\r\n", "\r\nα\r\nβ\r\n")]
        [InlineData("I am a amin_21 and how are you ali_lg? Are you good?", "I am a amin_21 and how are you ali_lg? Are you good?")]
        [InlineData("I am a amin_21 and how are you Reza_a? Are you nima_jx good?", "I am a amin₂₁ and how are you Rezaₐ? Are you nimaⱼₓ good?")]
        [InlineData(@"\mathbf{F}", "F")]
        [InlineData(@"\mathit{x}", "x")]
        [InlineData(@"\mathsf{T}", "T")]
        [InlineData(@"\mathtt{v}", "v")]
        [InlineData(@"\mathfrak{C}", "ℭ")]
        [InlineData(@"\mathscr{H}", "ℋ")]
        [InlineData(@"\overline{p}", "p̅")]
        [InlineData(@"\overline{xyz}", "xyz̅")]
        [InlineData(@"a\,b", "a b")]
        [InlineData(@"\sin \theta", "sin(θ)")]
        [InlineData(@"\sin \theta * \cos \phi", "sin(θ) * cos(φ)")]
        [InlineData(@"\cos \alpha", "cos(α)")]
        [InlineData(@"\tan \beta", "tan(β)")]
        [InlineData(@"The vertical component of the vector is labeled as (|v_y| = v \sin \theta). The angle (\theta) is marked between the vector and the horizontal axis.", @"The vertical component of the vector is labeled as (|v_y| = v sin(θ)). The angle (θ) is marked between the vector and the horizontal axis.")]
        [InlineData("A baryon consists of ____ quark(s) and ____ antiquark(s).", "A baryon consists of ____ quark(s) and ____ antiquark(s).")]
        [InlineData(@"K^+", "K⁺")]
        [InlineData(@"\sqrt[3]{x}", "∛x")]
        [InlineData(@"\sqrt[4]{y^2 + z^3}", "∜(y² + z³)")]
        [InlineData(@"\sqrt[2]{m}", "√m")]
        [InlineData(@"\sqrt{q}", "√q")]
        [InlineData(@"\sqrt[31]{y^2 + z^3}", "³¹√(y² + z³)")]
        [InlineData(@"\(F\)", "F")]
        [InlineData(@"\[x^2\]", "x²")]
        //[InlineData(@"\(a_{sub}\)", "a_sub")]
        public void ConvertToHumanFriendlyText_ConvertsCorrectly(string input, string expected)
        {
            var result = _converter.ConvertToHumanFriendlyText(input);
            Assert.Equal(expected, result);
        }
    }
}
