using Xunit;

namespace LatexConverter.Tests
{
    public class ConvertHumanToLatexTests
    {
        private readonly LaTexConverter _converter = new LaTexConverter();

        [Theory]
        [InlineData("α", @"\alpha ")]
        [InlineData("β", @"\beta ")]
        [InlineData("γ", @"\gamma ")]
        [InlineData("x²", "x^2")]
        [InlineData("a⁺", "a^+")]
        [InlineData("H₂O", @"H_2O")]
        [InlineData("Fₖ", @"F_k")]
        [InlineData("43°", @"43\circ ")]
        [InlineData("hello", "hello")]
        [InlineData("a b", "a b")]
        [InlineData("The equation is α² + β² = γ².", @"The equation is \alpha ^2 + \beta ^2 = \gamma ^2.")]
        [InlineData("Is it true that ∀ x ∈ ℝ, x² ≥ 0?", @"Is it true that \forall  x \in  \mathbb{R}, x^2 \geq  0?")]
        [InlineData("This is a vector: F⃗.", @"This is a vector: \vec{F}.")]
        [InlineData("The angle is 90°.", @"The angle is 90\circ.")]
        [InlineData("The subset symbol is ⊂.", @"The subset symbol is \subset.")]
        [InlineData("The result is approximately ≈ 5.", @"The result is approximately \approx  5.")]
        [InlineData("This is a test with a mix of symbols: α, β, γ.", @"This is a test with a mix of symbols: \alpha, \beta, \gamma.")]
        [InlineData("The integral is ∫ₐᵇ f(x) dx.", @"The integral is \int _a^b f(x) dx.")]
        [InlineData("This is a test of the not symbol: ¬A.", @"This is a test of the not symbol: \neg A.")]
        [InlineData("The result is ∞.", @"The result is \infty.")]
        [InlineData("This is a test of the prime symbol: f′.", @"This is a test of the prime symbol: f\prime.")]
        [InlineData("This is a test of the greater than or equal to symbol: ≥.", @"This is a test of the greater than or equal to symbol: \geq.")]
        [InlineData("This is a test of the less than or equal to symbol: ≤.", @"This is a test of the less than or equal to symbol: \leq.")]
        [InlineData("The vector component is vᵧ.", @"The vector component is v_\gamma.")]
        [InlineData("vᵧ", @"v_\gamma")]
        [InlineData("|vᵧ| = v sin(θ)", @"|v_\gamma| = v sin(\theta )")]
        [InlineData("k", "k")]
        [InlineData("√(x)", @"\sqrt{x}")]
        [InlineData("1 / 2", @"1 / 2")]
        [InlineData("aᵇ⁺ᶜ", @"a^{b+c}")]
        [InlineData("x¹⁰", @"x^{10}")]
        [InlineData("F⃗", @"\vec{F} ")]
        [InlineData("x̂", @"\hat{x} ")]
        [InlineData("ℰ₁", @"\mathcal{E} _1")]
        [InlineData("ℝ", @"\mathbb{R} ")]
        [InlineData("N", "N")]
        [InlineData("v⃗₀", @"\vec{v} _0")]
        [InlineData("a^(bᶜ)", @"a^(b^c)")]
        [InlineData("√(a²+b²) / 2", @"\sqrt{a^2+b^2} / 2")]
        [InlineData("∑ᵢ₌₁ⁿ i²", @"\sum _{i=1}^n i^2")]
        [InlineData("∫₀^(∞) e⁻ˣ dx", @"\int _0^(\infty ) e^{-x} dx")]
        [InlineData("a / b", "a / b")]
        [InlineData("90°", @"90\circ ")]
        [InlineData("x_f", "x_f")]
        [InlineData("xᵢ = 0", @"x_i = 0")]
        [InlineData("k = 52 N/m.", "k = 52 N/m.")]
        [InlineData("4.0 × 10⁻⁴", @"4.0 \times  10^{-4}")]
        [InlineData("sin⁻¹", @"\arcsin ")]
        [InlineData("cos⁻¹", @"\arccos ")]
        [InlineData("tan⁻¹", @"\arctan ")]
        [InlineData("rod: dEₓ = -k * λ * x * dx / (a² + x²)^(3/2).", @"rod: dE_x = -k * \lambda  * x * dx / (a^2 + x^2)^(3/2).")]
        [InlineData("V(r) = (q / (4 * π * ε₀ * a₀)) * exp(-2 * r / a₀) * (1 + a₀/r).", @"V(r) = (q / (4 * \pi  * \epsilon _0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).")]
        [InlineData("sin⁻¹[(λ / (d * π)) * cos⁻¹(√(I / I₀))]", @"\arcsin [(\lambda  / (d * \pi )) * \arccos (\sqrt{I / I_0})]")]
        [InlineData("μₖ", @"\mu _k")]
        [InlineData("x₁", "x_1")]
        [InlineData("λ₁", @"\lambda _1")]
        [InlineData("λ₁ + λ₂ = 1", @"\lambda _1 + \lambda _2 = 1")]
        [InlineData("√(ω₁ / ω₂)", @"\sqrt{\omega _1 / \omega _2}")]
        [InlineData("α + β", @"\alpha  + \beta ")]
        [InlineData("Δ - γ", @"\Delta  - \gamma ")]
        [InlineData("α² + β² = γ²", @"\alpha ^2 + \beta ^2 = \gamma ^2")]
        [InlineData("sin(θ) * cos(φ)", @"sin(\theta ) * cos(\phi )")]
        [InlineData("π * r²", @"\pi  * r^2")]
        [InlineData("κ", @"\kappa ")]
        [InlineData("a=b", "a=b")]
        [InlineData("Fₙₑₜ = m · a", @"F_{net} = m \cdot  a")]
        [InlineData("α / β", @"\alpha  / \beta ")]
        [InlineData("√(a² + b²)", @"\sqrt{a^2 + b^2}")]
        [InlineData("F⃗ᵢ", @"\vec{F} _i")]
        [InlineData("a ± b", @"a \pm  b")]
        [InlineData("a ≠ b", @"a \neq  b")]
        [InlineData("a ≥ b", @"a \geq  b")]
        [InlineData("∀ x", @"\forall  x")]
        [InlineData("∃ y", @"\exists  y")]
        [InlineData("z ∈ S", @"z \in  S")]
        [InlineData("∇ f", @"\nabla  f")]
        [InlineData("∂ f", @"\partial  f")]
        [InlineData("a ∓ b", @"a \mp  b")]
        [InlineData("a ≡ b", @"a \equiv  b")]
        [InlineData("∫ₐᵇ f(x) dx", @"\int _a^b f(x) dx")]
        [InlineData("lim_{x→∞} f(x)", @"\lim_{x\rightarrow \infty } f(x)")]
        [InlineData("(a b)\n(c d)", @"\begin{pmatrix} a & b \\ c & d \end{pmatrix}")]
        [InlineData("eˣ", "e^x")]
        [InlineData("det(A)", "det(A)")]
        [InlineData("(n k)", @"\binom{n}{k}")]
        [InlineData("∪", @"\cup ")]
        [InlineData("∩", @"\cap ")]
        [InlineData("⊂", @"\subset ")]
        [InlineData("⊃", @"\supset ")]
        [InlineData("¬A", @"\neg A")]
        [InlineData("A ∧ B", @"A \land  B")]
        [InlineData("A ∨ B", @"A \lor  B")]
        [InlineData("ħ", @"\hbar ")]
        [InlineData("ℓ", @"\ell ")]
        [InlineData("⊗", @"\otimes ")]
        [InlineData("∥", @"\parallel ")]
        [InlineData("⊥", @"\perp ")]
        [InlineData("⇒", @"\Rightarrow ")]
        [InlineData("⇔", @"\Leftrightarrow ")]
        [InlineData("ℜ", @"\Re ")]
        [InlineData("ℑ", @"\Im ")]
        [InlineData("⊙", @"\odot ")]
        [InlineData("≈", @"\approx ")]
        [InlineData("→", @"\rightarrow ")]
        [InlineData("←", @"\leftarrow ")]
        [InlineData("↑", @"\uparrow ")]
        [InlineData("↓", @"\downarrow ")]
        [InlineData("⇐", @"\Leftarrow ")]
        [InlineData("↔", @"\leftrightarrow ")]
        [InlineData("This ⇒ that and this ⇔ this.", @"This \Rightarrow  that and this \Leftrightarrow  this.")]
        [InlineData("Move → or ←.", @"Move \rightarrow  or \leftarrow.")]
        [InlineData("An ↑ and a ↓.", @"An \uparrow  and a \downarrow.")]
        [InlineData("A ⇒ B ⇐ C.", @"A \Rightarrow  B \Leftarrow  C.")]
        [InlineData("A ↔ B ⇔ C.", @"A \leftrightarrow  B \Leftrightarrow  C.")]
        [InlineData("The vector is ⊥ to the plane.", @"The vector is \perp  to the plane.")]
        [InlineData("The lines are ∥.", @"The lines are \parallel.")]
        [InlineData("This is a ⊙ operation.", @"This is a \odot  operation.")]
        [InlineData("The ℜ part and the ℑ part.", @"The \Re  part and the \Im  part.")]
        [InlineData("A ∪ B and C ∩ D", @"A \cup  B and C \cap  D")]
        [InlineData("E ⊂ F and G ⊃ H", @"E \subset  F and G \supset  H")]
        [InlineData("¬I ∧ J ∨ K", @"\neg I \land  J \lor  K")]
        [InlineData("The value of ħ is constant, as is ℓ.", @"The value of \hbar  is constant, as is \ell.")]
        [InlineData("♣", @"\clubsuit ")]
        [InlineData("♦", @"\diamondsuit ")]
        [InlineData("♥", @"\heartsuit ")]
        [InlineData("♠", @"\spadesuit ")]
        [InlineData("♭", @"\flat ")]
        [InlineData("♮", @"\natural ")]
        [InlineData("♯", @"\sharp ")]
        [InlineData("∠", @"\angle ")]
        [InlineData("∡", @"\measuredangle ")]
        [InlineData("f′", @"f\prime ")]
        [InlineData("…", @"\dots ")]
        [InlineData("⋯", @"\cdots ")]
        [InlineData("⋮", @"\vdots ")]
        [InlineData("⋱", @"\ddots ")]
        [InlineData("■", @"\blacksquare ")]
        [InlineData("△", @"\triangle ")]
        [InlineData("▽", @"\triangledown ")]
        [InlineData("\r\nα\r\nβ\r\n", "\r\n\\alpha \r\n\\beta \r\n")]
        [InlineData("slope until x₂.", "slope until x_2.")]
        [InlineData("and n₂. A light ray", "and n_2. A light ray")]
        [InlineData("a\r\nb", "a\r\nb")]
        [InlineData("I am a amin₂₁ and how are you Rezaₐ? Are you nimaⱼₓ good?", "I am a amin_{21} and how are you Reza_a? Are you nima_{jx} good?")]
        [InlineData("F", "F")]
        [InlineData("x", "x")]
        [InlineData("T", "T")]
        [InlineData("ℭ", @"\mathfrak{C} ")]
        [InlineData("ℋ", @"\mathcal{H} ")]
        [InlineData("p̅", @"\overline{p}")]
        [InlineData("xyz̅", @"\overline{xyz}")]
        [InlineData(@"The vertical component of the vector is labeled as (|v_y| = v sin(θ)). The angle (θ) is marked between the vector and the horizontal axis.", @"The vertical component of the vector is labeled as (|v_y| = v sin(\theta )). The angle (\theta ) is marked between the vector and the horizontal axis.")]
        [InlineData("K⁺", "K^+")]
        [InlineData("The formula for water is H₂O.", "The formula for water is H_2O.")]
        [InlineData("The equation x¹ + y¹ = z¹ is simple.", "The equation x^1 + y^1 = z^1 is simple.")]
        [InlineData("The equation is E = mc².", "The equation is E = mc^2.")]
        [InlineData("This is the sum: ∑ᵢ₌₁ⁿ i.", @"This is the sum: \sum _{i=1}^n i.")]
        [InlineData("Let's test a fraction: 1/2.", "Let's test a fraction: 1/2.")]
        public void ConvertHumanToLatex_ConvertsCorrectly(string input, string expected)
        {
            var result = _converter.ConvertHumanToLatex(input);
            Assert.Equal(expected, result);
        }
    }
}
