using Xunit;

namespace LatexConverter.Tests
{
    public class ConvertToOpenAIFriendlyTextTests
    {
        private readonly LaTexConverter _converter = new LaTexConverter();

        [Theory]
        [InlineData(@"\textrm{k}", "k")]
        [InlineData(@"\(F_\textrm{k}\)", "F_k")]
        [InlineData(@"43^\circ", "43 degrees")]
        [InlineData(@"\alpha", "alpha")]
        [InlineData(@"\sqrt{x}", "sqrt(x)")]
        [InlineData(@"\frac{1}{2}", "1/2")]
        [InlineData(@"a^{b+c}", "a^(b+c)")]
        [InlineData(@"x^{10}", "x^10")]
        [InlineData(@"\vec{v}", "vec(v)")]
        [InlineData(@"\hat{x}", "hat(x)")]
        [InlineData(@"\mathcal{E}_1", "mathcal(E)_1")]
        [InlineData(@"\mathbb{R}", "mathbb(R)")]
        [InlineData(@"\text{hello}", "hello")]
        [InlineData(@"\mathrm{N}", "N")]
        [InlineData(@"\vec{v}_0", "vec(v)_0")]
        [InlineData(@"a^{b^{c}}", "a^(b^c)")]
        [InlineData(@"\frac{\sqrt{a^2+b^2}}{2}", "sqrt(a^2+b^2)/2")]
        [InlineData(@"\sum_{i=1}^{n} i^2", "summation_(i=1)^(n) i^2")]
        [InlineData(@"\int_{0}^{\infty} e^{-x} dx", "integral_(0)^(infty) e^(-x) dx")]
        [InlineData(@"\forall x \in \mathbb{R}", "forall x in mathbb(R)")]
        [InlineData(@"\bigg( \frac{a}{b} \bigg)", "a/b")]
        [InlineData(@"90^\circ", "90 degrees")]
        [InlineData(@"\(x_f\)", "x_f")]
        [InlineData(@"\(x_i = 0\)", "x_i = 0")]
        [InlineData(@"\(k = 52\;\mathrm{N}/\mathrm{m}\).", "k = 52 N/m.")]
        [InlineData(@"\(v\)", "v")]
        [InlineData("a\nb", "a\nb")]
        [InlineData("E = mc^2", "E = mc^2")]
        [InlineData("4.0 \\times 10^{-4}", "4.0 times 10^(-4)")]
        [InlineData("sin^(-1)", "arcsin")]
        [InlineData("cos^(-1)", "arccos")]
        [InlineData("tan^(-1)", "arctan")]
        [InlineData("sqrt(x)", "sqrt(x)")]
        [InlineData("A small segment of the wire is marked in blue as \"d-x.\"", "A small segment of the wire is marked in blue as \"d-x.\"")]
        [InlineData("An x-y coordinate system is shown in the top right", "An x-y coordinate system is shown in the top right")]
        [InlineData("rod: dE_x = -k * lambda * x * dx / (a^2 + x^2)^(3/2).", "rod: dE_x = -k * lambda * x * dx / (a^2 + x^2)^(3/2).")]
        [InlineData("V(r) = (q / (4 * \\pi * \\epsilon_0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).", "V(r) = (q / (4 * pi * epsilon_0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).")]
        [InlineData("sin^(-1) [ (lambda / (d * pi)) * cos^(-1) (sqrt(I / I_0)) ]", "arcsin [ (lambda / (d * pi)) * arccos (sqrt(I / I_0)) ]")]
        [InlineData("the quantity (x/2 squared plus l squared) raised to the 3/2 power", "the quantity (x/2 squared plus l squared) raised to the 3/2 power")]
        [InlineData("y_ob to a", "y_ob to a")]
        // [InlineData(@"a \pm b", "a pm b")]
        [InlineData(@"a \pm b", "a ± b")]
        [InlineData(@"a \neq b", "a neq b")]
        [InlineData(@"a \geq b", "a geq b")]
        [InlineData(@"\forall x", "forall x")]
        [InlineData(@"\exists y", "exists y")]
        [InlineData(@"z \in S", "z in S")]
        [InlineData(@"\nabla f", "nabla f")]
        [InlineData(@"\partial f", "partial f")]
        [InlineData(@"a \mp b", "a mp b")]
        [InlineData(@"a \equiv b", "a equiv b")]
        [InlineData(@"\int_a^b f(x) dx", "integral_(a)^(b) f(x) dx")]
        [InlineData(@"\lim_{x \to \infty} f(x)", "limit_(x -> infty) f(x)")]
        [InlineData(@"\begin{pmatrix} a & b \\ c & d \end{pmatrix}", "matrix[[a, b], [c, d]]")]
        [InlineData(@"\sin(x)", "sin(x)")]
        [InlineData(@"\cos(x)", "cos(x)")]
        [InlineData(@"\tan(x)", "tan(x)")]
        [InlineData(@"\log(x)", "log(x)")]
        [InlineData(@"\ln(x)", "ln(x)")]
        [InlineData(@"\exp(x)", "exp(x)")]
        [InlineData(@"\det(A)", "det(A)")]
        [InlineData(@"\binom{n}{k}", "binom(n,k)")]
        [InlineData(@"\cup", "cup")]
        [InlineData(@"\cap", "cap")]
        [InlineData(@"\subset", "subset")]
        [InlineData(@"\supset", "supset")]
        [InlineData(@"\neg A", "neg A")]
        [InlineData(@"A \land B", "A land B")]
        [InlineData(@"A \lor B", "A lor B")]
        [InlineData(@"\hbar", "hbar")]
        [InlineData(@"\ell", "ell")] 
        [InlineData(@"\otimes", "otimes")]
        [InlineData(@"\parallel", "parallel")]
        [InlineData(@"\perp", "perp")]
        [InlineData(@"\implies", "implies")]
        [InlineData(@"\iff", "iff")]
        [InlineData(@"\Re", "Re")]
        [InlineData(@"\Im", "Im")]
        [InlineData(@"\odot", "odot")]
        [InlineData(@"\approx", "approx")]
        [InlineData(@"\rightarrow", "rightarrow")]
        [InlineData(@"\leftarrow", "leftarrow")]
        [InlineData(@"\uparrow", "uparrow")]
        [InlineData(@"\downarrow", "downarrow")]
        [InlineData(@"\Rightarrow", "Rightarrow")]
        [InlineData(@"\Leftarrow", "Leftarrow")]
        [InlineData(@"\leftrightarrow", "leftrightarrow")]
        [InlineData(@"\Leftrightarrow", "Leftrightarrow")]
        [InlineData(@"The result is \approx 5.", "The result is approx 5.")]
        [InlineData(@"This \implies that and this \iff this.", "This implies that and this iff this.")]
        [InlineData(@"Move \rightarrow or \leftarrow.", "Move rightarrow or leftarrow.")]
        [InlineData(@"An \uparrow and a \downarrow.", "An uparrow and a downarrow.")]
        [InlineData(@"A \Rightarrow B \Leftarrow C.", "A Rightarrow B Leftarrow C.")]
        [InlineData(@"A \leftrightarrow B \Leftrightarrow C.", "A leftrightarrow B Leftrightarrow C.")]
        [InlineData(@"The vector is \perp to the plane.", "The vector is perp to the plane.")]
        [InlineData(@"The lines are \parallel.", "The lines are parallel.")]
        [InlineData(@"This is a \odot operation.", "This is a odot operation.")]
        [InlineData(@"The \Re part and the \Im part.", "The Re part and the Im part.")]
        [InlineData(@"A \cup B and C \cap D", "A cup B and C cap D")]
        [InlineData(@"E \subset F and G \supset H", "E subset F and G supset H")]
        [InlineData(@"\neg I \land J \lor K", "neg I land J lor K")]
        [InlineData(@"The value of \hbar is constant, as is \ell.", "The value of hbar is constant, as is ell.")]
        [InlineData(@"\clubsuit", "clubsuit")]
        [InlineData(@"\diamondsuit", "diamondsuit")]
        [InlineData(@"\heartsuit", "heartsuit")]
        [InlineData(@"\spadesuit", "spadesuit")]
        [InlineData(@"\flat", "flat")]
        [InlineData(@"\natural", "natural")]
        [InlineData(@"\sharp", "sharp")]
        [InlineData(@"\angle", "angle")]
        [InlineData(@"\measuredangle", "measuredangle")]
        [InlineData(@"f^\prime", "f prime")]
        // [InlineData(@"\dots", "...")]
        [InlineData(@"\dots", "dots")]
        // [InlineData(@"\cdots", "...")]
        [InlineData(@"\cdots", "cdots")]
        // [InlineData(@"\vdots", "...")]
        [InlineData(@"\vdots", "vdots")]
        // [InlineData(@"\ddots", "...")]
        [InlineData(@"\ddots", "ddots")]
        [InlineData(@"\blacksquare", "blacksquare")]
        [InlineData(@"\triangle", "triangle")]
        [InlineData(@"\triangledown", "triangledown")]
        [InlineData("a\r\nb", "a\r\nb")]
        [InlineData("\r\n\\alpha\r\n\\beta\r\n", "\r\nalpha\r\nbeta\r\n")]
        [InlineData(@"\mathbf{F}", "F")]
        [InlineData(@"\mathit{x}", "x")]
        [InlineData(@"\mathsf{T}", "T")]
        [InlineData(@"\mathtt{v}", "v")]
        [InlineData(@"\mathfrak{g}", "g")]
        [InlineData(@"\mathscr{L}", "L")]
        [InlineData(@"\overline{p}", "overline(p)")]
        [InlineData(@"\overline{xyz}", "overline(xyz)")]
        [InlineData(@"a\,b", "a b")]
        [InlineData(@"\sin \theta", "sin(theta)")]
        [InlineData(@"\cos \alpha", "cos(alpha)")]
        [InlineData(@"\tan \beta", "tan(beta)")]
        [InlineData("A baryon consists of ____ quark(s) and ____ antiquark(s).", "A baryon consists of ____ quark(s) and ____ antiquark(s).")]
        public void ConvertToOpenAIFriendlyText_ConvertsCorrectly(string input, string expected)
        {
            var result = _converter.ConvertToOpenAIFriendlyText(input);
            Assert.Equal(expected, result);
        }

        [Theory]
        [InlineData(@"\[x_f\]", "x_f")]
        [InlineData(@"\[x_i = 0\]", "x_i = 0")]
        [InlineData(@"$x_f$", "x_f")]
        [InlineData(@"$x_i = 0$", "x_i = 0")]
        [InlineData(@"$$x_f$$", "x_f")]
        [InlineData(@"$$x_i = 0$$", "x_i = 0")]
        //[InlineData(@"% this is a comment", "")]
        //[InlineData(@"\alpha % this is a comment", "alpha")]
        public void ConvertToOpenAIFriendlyText_HandlesDelimitersAndComments(string input, string expected)
        {
            var result = _converter.ConvertToOpenAIFriendlyText(input);
            Assert.Equal(expected, result);
        }
    }
}
