using Xunit;

namespace LatexConverter.Tests
{
    public class ConvertToScreenReaderFriendlyTextTests
    {
        private readonly LaTexConverter _converter = new LaTexConverter();

        [Theory]
        [InlineData(@"\textrm{k}", "k")]
        [InlineData(@"F_\textrm{k}", "F subscript k")]
        [InlineData(@"43^\circ", "43 degrees")]
        [InlineData(@"\alpha", "alpha")]
        [InlineData(@"\sqrt{x}", "the square root of x")]
        [InlineData(@"\frac{1}{2}", "fraction with numerator 1 and denominator 2")]
        [InlineData(@"a^{b+c}", "a to the power of b plus c")]
        [InlineData(@"x^{10}", "x to the power of 10")]
        [InlineData(@"x^{2}", "x squared")]
        [InlineData(@"\vec{v}", "vector v")]
        [InlineData(@"\hat{x}", "x hat")]
        [InlineData(@"\mathcal{E}_1", "calligraphic E subscript 1")]
        [InlineData(@"\mathbb{R}", "the set of real numbers")]
        [InlineData(@"\text{hello}", "hello")]
        [InlineData(@"\mathrm{N}", "N")]
        [InlineData(@"\vec{v}_0", "vector v subscript 0")]
        [InlineData(@"a^{b^{c}}", "a to the power of b to the power of c")]
        [InlineData(@"\frac{\sqrt{a^2+b^2}}{2}", "fraction with numerator the square root of a squared plus b squared and denominator 2")]
        [InlineData(@"\sum_{i=1}^{n} i^2", "summation from i equals 1 to n i squared")]
        [InlineData(@"\int_{0}^{\infty} e^{-x} dx", "integral from 0 to infinity e to the power of minus x dx")]
        [InlineData(@"\forall x \in \mathbb{R}", "for all x in the set of real numbers")]
        [InlineData(@"\bigg( \frac{a}{b} \bigg)", "fraction with numerator a and denominator b")]
        [InlineData(@"90^\circ", "90 degrees")]
        [InlineData(@"\(x_f\)", "x subscript f")]
        [InlineData(@"\(x_i = 0\)", "x subscript i equals 0")]
        [InlineData(@"\(k = 52\;\mathrm{N}/\mathrm{m}\).", "k equals 52 N divided by m.")]
        [InlineData(@"\(v\)", "v")]
        [InlineData("a\nb", "a\nb")]
        [InlineData("E = mc^2", "E equals mc squared")]
        [InlineData("4.0 \\times 10^{-4}", "4.0 times 10 to the power of minus 4")]
        [InlineData("sin^(-1)", "arcsin")]
        [InlineData("cos^(-1)", "arccos")]
        [InlineData("tan^(-1)", "arctan")]
        [InlineData("sqrt(x)", "the square root of x")]
        [InlineData("A small segment of the wire is marked in blue as \"d-x.\"", "A small segment of the wire is marked in blue as \"d-x.\"")]
        [InlineData("An x-y coordinate system is shown in the top right", "An x-y coordinate system is shown in the top right")]
        [InlineData("rod: dE_x = -k * lambda * x * dx / (a^2 + x^2)^(3/2).", "rod: dE subscript x equals minus k times lambda times x times dx divided by (a squared plus x squared) to the power of (3 divided by 2).")]
        [InlineData("V(r) = (q / (4 * \\pi * \\epsilon_0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).", "V(r) equals (q divided by (4 times pi times epsilon subscript 0 times a subscript 0)) times exp(minus 2 times r divided by a subscript 0) times (1 plus a subscript 0 divided by r).")]
        [InlineData(
            "sin^(-1) [ (lambda / (d * pi)) * cos^(-1) (sqrt(I / I_0)) ]",
            "arcsin [ (lambda divided by (d times pi)) times arccos (the square root of I divided by I subscript 0) ]")]
        [InlineData("the quantity (x/2 squared plus l squared) raised to the 3/2 power", "the quantity (x divided by 2 squared plus l squared) raised to the 3 divided by 2 power")]
        [InlineData("y_ob to a", "y subscript ob to a")]
        [InlineData(@"\mu_k", "mu subscript k")]
        [InlineData(@"\geq", "greater than or equal to")]
        [InlineData("(-2)", "(minus 2)")]
        [InlineData("(a+b)", "(a plus b)")]
        [InlineData(@"a \pm b", "a plus-minus b")]
        [InlineData(@"a \neq b", "a not equal to b")]
        [InlineData(@"a \geq b", "a greater than or equal to b")]
        [InlineData(@"\forall x", "for all x")]
        [InlineData(@"\exists y", "there exists y")]
        [InlineData(@"z \in S", "z in S")]
        [InlineData(@"\nabla f", "nabla f")]
        [InlineData(@"\partial f", "partial derivative f")]
        [InlineData(@"a \mp b", "a minus-plus b")]
        [InlineData(@"a \equiv b", "a congruent to b")]
        [InlineData(@"\int_a^b f(x) dx", "integral from a to b f(x) dx")]
        [InlineData(@"\lim_{x \to \infty} f(x)", "limit as x approaches infinity of f(x)")]
        [InlineData(@"\begin{pmatrix} a & b \\ c & d \end{pmatrix}", "a 2x2 matrix with rows (a, b) and (c, d)")]
        [InlineData(@"\sin(x)", "sine of x")]
        [InlineData(@"\cos(x)", "cosine of x")]
        [InlineData(@"\tan(x)", "tangent of x")]
        [InlineData(@"\log(x)", "logarithm of x")]
        [InlineData(@"\ln(x)", "natural logarithm of x")]
        [InlineData(@"\exp(x)", "e to the power of x")]
        [InlineData(@"\det(A)", "determinant of A")]
        [InlineData(@"\binom{n}{k}", "n choose k")]
        [InlineData(@"\cup", "union")]
        [InlineData(@"\cap", "intersection")]
        [InlineData(@"\subset", "subset of")]
        [InlineData(@"\supset", "superset of")]
        [InlineData(@"\neg A", "not A")]
        [InlineData(@"A \land B", "A and B")]
        [InlineData(@"A \lor B", "A or B")]
        [InlineData(@"\hbar", "h-bar")]
        [InlineData(@"\ell", "ell")]
        [InlineData(@"\otimes", "tensor product")]
        [InlineData(@"\parallel", "parallel to")]
        [InlineData(@"\perp", "perpendicular to")]
        [InlineData(@"\implies", "implies")]
        [InlineData(@"\iff", "if and only if")]
        [InlineData(@"\Re", "Real part")]
        [InlineData(@"\Im", "Imaginary part")]
        [InlineData(@"\odot", "circled dot")]
        [InlineData(@"\approx", "approximately equal to")]
        [InlineData(@"\rightarrow", "right arrow")]
        [InlineData(@"\leftarrow", "left arrow")]
        [InlineData(@"\uparrow", "up arrow")]
        [InlineData(@"\downarrow", "down arrow")]
        [InlineData(@"\Rightarrow", "right double arrow")]
        [InlineData(@"\Leftarrow", "left double arrow")]
        [InlineData(@"\leftrightarrow", "left right arrow")]
        [InlineData(@"\Leftrightarrow", "if and only if")]
        [InlineData(@"The result is \approx 5.", "The result is approximately equal to 5.")]
        [InlineData(@"This \implies that and this \iff this.", "This implies that and this if and only if this.")]
        [InlineData(@"Move \rightarrow or \leftarrow.", "Move right arrow or left arrow.")]
        [InlineData(@"An \uparrow and a \downarrow.", "An up arrow and a down arrow.")]
        [InlineData(@"A \Rightarrow B \Leftarrow C.", "A right double arrow B left double arrow C.")]
        [InlineData(@"A \leftrightarrow B \Leftrightarrow C.", "A left right arrow B if and only if C.")]
        [InlineData(@"The vector is \perp to the plane.", "The vector is perpendicular to to the plane.")]
        [InlineData(@"The lines are \parallel.", "The lines are parallel to.")]
        [InlineData(@"This is a \odot operation.", "This is a circled dot operation.")]
        [InlineData(@"The \Re part and the \Im part.", "The Real part part and the Imaginary part part.")]
        [InlineData(@"A \cup B and C \cap D", "A union B and C intersection D")]
        [InlineData(@"E \subset F and G \supset H", "E subset of F and G superset of H")]
        [InlineData(@"\neg I \land J \lor K", "not I and J or K")]
        [InlineData(@"The value of \hbar is constant, as is \ell.", "The value of h-bar is constant, as is ell.")]
        [InlineData(@"\clubsuit", "club suit")]
        [InlineData(@"\diamondsuit", "diamond suit")]
        [InlineData(@"\heartsuit", "heart suit")]
        [InlineData(@"\spadesuit", "spade suit")]
        [InlineData(@"\flat", "flat")]
        [InlineData(@"\natural", "natural")]
        [InlineData(@"\sharp", "sharp")]
        [InlineData(@"\angle", "angle")]
        [InlineData(@"\measuredangle", "measured angle")]
        [InlineData(@"f^\prime", "f prime")]
        [InlineData(@"\dots", "dots")]
        [InlineData(@"\cdots", "centered dots")]
        [InlineData(@"\vdots", "vertical dots")]
        [InlineData(@"\ddots", "diagonal dots")]
        [InlineData(@"\blacksquare", "black square")]
        [InlineData(@"\triangle", "triangle")]
        [InlineData(@"\triangledown", "downward triangle")]
        [InlineData("a\r\nb", "a\r\nb")]
        [InlineData("\r\n\\alpha\r\n\\beta\r\n", "\r\nalpha\r\nbeta\r\n")]
        [InlineData(@"\mathbf{F}", "bf F")]
        [InlineData(@"\mathit{x}", "it x")]
        [InlineData(@"\mathsf{T}", "sf T")]
        [InlineData(@"\mathtt{v}", "tt v")]
        [InlineData(@"\mathfrak{g}", "frak g")]
        [InlineData(@"\mathscr{L}", "scr L")]
        [InlineData(@"\overline{p}", "p bar")]
        [InlineData(@"\overline{xyz}", "xyz bar")]
        [InlineData(@"a\,b", "a b")]
        [InlineData(@"\sin \theta", "sine of theta")]
        [InlineData(@"\cos \alpha", "cosine of alpha")]
        [InlineData(@"\tan \beta", "tangent of beta")]
        [InlineData("A baryon consists of ____ quark(s) and ____ antiquark(s).", "A baryon consists of ____ quark(s) and ____ antiquark(s).")]
        [InlineData(@"K^+", "K plus")]
        [InlineData(@"e^-", "e minus")]
        [InlineData(@"A^{*}", "A star")]
        public void ConvertToScreenReaderFriendlyText_ConvertsCorrectly(string input, string expected)
        {
            var result = _converter.ConvertToScreenReaderFriendlyText(input);
            Assert.Equal(expected, result);
        }
    }
}
