using Xunit;

namespace LatexConverter.Tests
{
    public class LaTexConverterTests
    {
        private readonly LaTexConverter _converter = new LaTexConverter();

        [Theory]
        [InlineData(@"\textrm{k}", "k")]
        [InlineData(@"\(F_\textrm{k}\)", "F_k")]
        [InlineData(@"43^\circ", "43 degrees")]
        [InlineData(@"\alpha", "alpha")]
        [InlineData(@"\sqrt{x}", "sqrt(x)")]
        [InlineData(@"\frac{1}{2}", "1/2")]
        [InlineData(@"a^{b+c}", "a^(b+c)")]
        [InlineData(@"x^{10}", "x^10")]
        [InlineData(@"\vec{v}", "v")]
        [InlineData(@"\hat{x}", "hat x")]
        [InlineData(@"\mathcal{E}_1", "E_1")]
        [InlineData(@"\mathbb{R}", "R")]
        [InlineData(@"\text{hello}", "hello")]
        [InlineData(@"\mathrm{N}", "N")]
        [InlineData(@"\vec{v}_0", "v_0")]
        [InlineData(@"a^{b^{c}}", "a^(b^c)")]
        [InlineData(@"\frac{\sqrt{a^2+b^2}}{2}", "sqrt(a^2+b^2)/2")]
        [InlineData(@"\sum_{i=1}^{n} i^2", "summation_(i=1)^(n) i^2")]
        [InlineData(@"\int_{0}^{\infty} e^{-x} dx", "integral_(0)^(infty) e^(-x) dx")]
        [InlineData(@"\forall x \in \mathbb{R}", "forall x in R")]
        [InlineData(@"\bigg( \frac{a}{b} \bigg)", "a/b")]
        [InlineData(@"90^\circ", "90 degrees")]
        [InlineData(@"\(x_f\)", "x_f")]
        [InlineData(@"\(x_i = 0\)", "x_i = 0")]
        [InlineData(@"\(k = 52\;\mathrm{N}/\mathrm{m}\).", "k = 52 N/m.")]
        [InlineData(@"\(v\)", "v")]
        [InlineData("a\nb", "a\nb")]
        [InlineData("E = mc^2", "E = mc^2")]
        [InlineData("4.0 \\times 10^{-4}", "4.0 times 10^(-4)")]
        [InlineData("sin^(-1)", "arcsin")]
        [InlineData("cos^(-1)", "arccos")]
        [InlineData("tan^(-1)", "arctan")]
        [InlineData("sqrt(x)", "sqrt(x)")]
        [InlineData("A small segment of the wire is marked in blue as \"d-x.\"", "A small segment of the wire is marked in blue as \"d-x.\"")]
        [InlineData("An x-y coordinate system is shown in the top right", "An x-y coordinate system is shown in the top right")]
        [InlineData("rod: dE_x = -k * lambda * x * dx / (a^2 + x^2)^(3/2).", "rod: dE_x = -k * lambda * x * dx / (a^2 + x^2)^(3/2).")]
        [InlineData("V(r) = (q / (4 * \\pi * \\epsilon_0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).", "V(r) = (q / (4 * pi * epsilon_0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).")]
        [InlineData("sin^(-1) [ (lambda / (d * pi)) * cos^(-1) (sqrt(I / I_0)) ]", "arcsin [ (lambda / (d * pi)) * arccos (sqrt(I / I_0)) ]")]
        [InlineData("the quantity (x/2 squared plus l squared) raised to the 3/2 power", "the quantity (x/2 squared plus l squared) raised to the 3/2 power")]
        [InlineData("y_ob to a", "y_ob to a")]
        [InlineData(@"a \pm b", "a pm b")]
        [InlineData(@"a \neq b", "a neq b")]
        [InlineData(@"a \geq b", "a geq b")]
        [InlineData(@"\forall x", "forall x")]
        [InlineData(@"\exists y", "exists y")]
        [InlineData(@"z \in S", "z in S")]
        [InlineData(@"\nabla f", "nabla f")]
        [InlineData(@"\partial f", "partial f")]
        [InlineData(@"a \mp b", "a mp b")]
        [InlineData(@"a \equiv b", "a equiv b")]
        [InlineData(@"\int_a^b f(x) dx", "integral_(a)^(b) f(x) dx")]
        [InlineData(@"\lim_{x \to \infty} f(x)", "limit_(x -> infty) f(x)")]
        [InlineData(@"\begin{pmatrix} a & b \\ c & d \end{pmatrix}", "matrix[[a, b], [c, d]]")]
        [InlineData(@"\sin(x)", "sin(x)")]
        [InlineData(@"\cos(x)", "cos(x)")]
        [InlineData(@"\tan(x)", "tan(x)")]
        [InlineData(@"\log(x)", "log(x)")]
        [InlineData(@"\ln(x)", "ln(x)")]
        [InlineData(@"\exp(x)", "exp(x)")]
        [InlineData(@"\det(A)", "det(A)")]
        [InlineData(@"\binom{n}{k}", "binom(n,k)")]
        [InlineData(@"\cup", "cup")]
        [InlineData(@"\cap", "cap")]
        [InlineData(@"\subset", "subset")]
        [InlineData(@"\supset", "supset")]
        [InlineData(@"\neg A", "neg A")]
        [InlineData(@"A \land B", "A land B")]
        [InlineData(@"A \lor B", "A lor B")]
        [InlineData(@"\hbar", "hbar")]
        [InlineData(@"\ell", "ell")]
        [InlineData(@"\otimes", "otimes")]
        [InlineData(@"\parallel", "parallel")]
        [InlineData(@"\perp", "perp")]
        [InlineData(@"\implies", "implies")]
        [InlineData(@"\iff", "iff")]
        [InlineData(@"\Re", "Re")]
        [InlineData(@"\Im", "Im")]
        [InlineData(@"\odot", "odot")]
        [InlineData(@"\approx", "approx")]
        [InlineData(@"\rightarrow", "rightarrow")]
        [InlineData(@"\leftarrow", "leftarrow")]
        [InlineData(@"\uparrow", "uparrow")]
        [InlineData(@"\downarrow", "downarrow")]
        [InlineData(@"\Rightarrow", "Rightarrow")]
        [InlineData(@"\Leftarrow", "Leftarrow")]
        [InlineData(@"\leftrightarrow", "leftrightarrow")]
        [InlineData(@"\Leftrightarrow", "Leftrightarrow")]
        [InlineData(@"The result is \approx 5.", "The result is approx 5.")]
        [InlineData(@"This \implies that and this \iff this.", "This implies that and this iff this.")]
        [InlineData(@"Move \rightarrow or \leftarrow.", "Move rightarrow or leftarrow.")]
        [InlineData(@"An \uparrow and a \downarrow.", "An uparrow and a downarrow.")]
        [InlineData(@"A \Rightarrow B \Leftarrow C.", "A Rightarrow B Leftarrow C.")]
        [InlineData(@"A \leftrightarrow B \Leftrightarrow C.", "A leftrightarrow B Leftrightarrow C.")]
        [InlineData(@"The vector is \perp to the plane.", "The vector is perp to the plane.")]
        [InlineData(@"The lines are \parallel.", "The lines are parallel.")]
        [InlineData(@"This is a \odot operation.", "This is a odot operation.")]
        [InlineData(@"The \Re part and the \Im part.", "The Re part and the Im part.")]
        public void ConvertToOpenAIFriendlyText_ConvertsCorrectly(string input, string expected)
        {
            var result = _converter.ConvertToOpenAIFriendlyText(input);
            Assert.Equal(expected, result);
        }

        [Theory]
        [InlineData(@"\textrm{k}", "k")]
        [InlineData(@"F_\textrm{k}", "Fₖ")]
        [InlineData(@"43^\circ", "43°")]
        [InlineData(@"\alpha", "α")]
        [InlineData(@"\sqrt{x}", "√(x)")]
        [InlineData(@"\frac{1}{2}", "1 / 2")]
        [InlineData(@"a^{b+c}", "aᵇ⁺ᶜ")]
        [InlineData(@"x^{10}", "x¹⁰")]
        [InlineData(@"\vec{F}", "F⃗")]
        [InlineData(@"\hat{x}", "x̂")]
        [InlineData(@"\mathcal{E}_1", "ℰ₁")]
        [InlineData(@"\mathbb{R}", "ℝ")]
        [InlineData(@"\text{hello}", "hello")]
        [InlineData(@"\mathrm{N}", "N")]
        [InlineData(@"\vec{v}_0", "v⃗₀")]
        [InlineData(@"a^{b^{c}}", "a^(bᶜ)")]
        [InlineData(@"\frac{\sqrt{a^2+b^2}}{2}", "√(a²+b²) / 2")]
        [InlineData(@"\sum_{i=1}^{n} i^2", "∑ᵢ₌₁ⁿ i²")]
        [InlineData(@"\int_{0}^{\infty} e^{-x} dx", "∫₀^(∞) e⁻ˣ dx")]
        [InlineData(@"\forall x \in \mathbb{R}", "∀ x ∈ ℝ")]
        [InlineData(@"\bigg( \frac{a}{b} \bigg)", "a / b")]
        [InlineData(@"90^\circ", "90°")]
        [InlineData(@"\(x_f\)", "x_f")]
        [InlineData(@"\(x_i = 0\)", "xᵢ = 0")]
        [InlineData(@"\(k = 52\;\mathrm{N}/\mathrm{m}\).", "k = 52 N/m.")]
        [InlineData(@"\(v\)", "v")]
        [InlineData("a\nb", "a\nb")]
        [InlineData("E = mc^2", "E = mc²")]
        [InlineData("4.0 \\times 10^{-4}", "4.0 × 10⁻⁴")]
        [InlineData("sin^(-1)", "sin⁻¹")]
        [InlineData("cos^(-1)", "cos⁻¹")]
        [InlineData("tan^(-1)", "tan⁻¹")]
        [InlineData("sqrt(x)", "√(x)")]
        [InlineData("A small segment of the wire is marked in blue as \"d-x.\"", "A small segment of the wire is marked in blue as \"d-x.\"")]
        [InlineData("An x-y coordinate system is shown in the top right", "An x-y coordinate system is shown in the top right")]
        [InlineData("rod: dE_x = -k * lambda * x * dx / (a^2 + x^2)^(3/2).", "rod: dEₓ = -k * λ * x * dx / (a² + x²)^(3/2).")]
        [InlineData("V(r) = (q / (4 * \\pi * \\epsilon_0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).", "V(r) = (q / (4 * π * ε₀ * a₀)) * exp(-2 * r / a₀) * (1 + a₀/r).")]
        [InlineData(
            "sin^(-1) [ (lambda / (d * pi)) * cos^(-1) (sqrt(I / I_0)) ]",
            "sin⁻¹[(λ / (d * π)) * cos⁻¹(√(I / I₀))]")]
        [InlineData("the quantity (x/2 squared plus l squared) raised to the 3/2 power", "the quantity (x/2 squared plus l squared) raised to the 3/2 power")]
        [InlineData("y_ob to a", "y_ob to a")]
        [InlineData(@"\mu_k", "μₖ")]
        [InlineData("H_2O", "H₂O")]
        [InlineData("x_1", "x₁")]
        [InlineData("lambda_1", "λ₁")]
        [InlineData("lambda_1 + lambda_2 = 1", "λ₁ + λ₂ = 1")]
        [InlineData("sqrt(omega_1 / omega_2)", "√(ω₁ / ω₂)")]
        [InlineData("alpha + beta", "α + β")]
        [InlineData("Delta - gamma", "Δ - γ")]
        [InlineData("alpha^2 + beta^2 = gamma^2", "α² + β² = γ²")]
        [InlineData("sin(theta) * cos(phi)", "sin(θ) * cos(φ)")]
        [InlineData("pi * r^2", "π * r²")]
        [InlineData("kappa", "κ")]
        [InlineData("+q", "+q")]
        [InlineData("a+b", "a+b")]
        [InlineData("a - b", "a - b")]
        [InlineData("a=b", "a=b")]
        [InlineData("F_{net} = m \\cdot a", "Fₙₑₜ = m · a")]
        [InlineData("\\frac{\\alpha}{\\beta}", "α / β")]
        [InlineData("\\sqrt{a^2 + b^2}", "√(a² + b²)")]
        [InlineData("sqrt(a^2 + b^2)", "√(a² + b²)")]
        [InlineData("\\vec{F}_i", "F⃗ᵢ")]
        [InlineData(@"a \pm b", "a ± b")]
        [InlineData(@"a \neq b", "a ≠ b")]
        [InlineData(@"a \geq b", "a ≥ b")]
        [InlineData(@"\forall x", "∀ x")]
        [InlineData(@"\exists y", "∃ y")]
        [InlineData(@"z \in S", "z ∈ S")]
        [InlineData(@"\nabla f", "∇ f")]
        [InlineData(@"\partial f", "∂ f")]
        [InlineData(@"a \mp b", "a ∓ b")]
        [InlineData(@"a \equiv b", "a ≡ b")]
        [InlineData(@"\int_a^b f(x) dx", "∫ₐᵇ f(x) dx")]
        [InlineData(@"\lim_{x \to \infty} f(x)", "lim_{x→∞} f(x)")]
        [InlineData(@"\begin{pmatrix} a & b \\ c & d \end{pmatrix}", "(a b)\n(c d)")]
        [InlineData(@"\sin(x)", "sin(x)")]
        [InlineData(@"\cos(x)", "cos(x)")]
        [InlineData(@"\tan(x)", "tan(x)")]
        [InlineData(@"\log(x)", "log(x)")]
        [InlineData(@"\ln(x)", "ln(x)")]
        [InlineData(@"\exp(x)", "eˣ")]
        [InlineData(@"\det(A)", "det(A)")]
        [InlineData(@"\binom{n}{k}", "(n k)")]
        [InlineData(@"\cup", "∪")]
        [InlineData(@"\cap", "∩")]
        [InlineData(@"\subset", "⊂")]
        [InlineData(@"\supset", "⊃")]
        [InlineData(@"\neg A", "¬A")]
        [InlineData(@"A \land B", "A ∧ B")]
        [InlineData(@"A \lor B", "A ∨ B")]
        [InlineData(@"\hbar", "ħ")]
        [InlineData(@"\ell", "ℓ")]
        [InlineData(@"\otimes", "⊗")]
        [InlineData(@"\parallel", "∥")]
        [InlineData(@"\perp", "⊥")]
        [InlineData(@"\implies", "⇒")]
        [InlineData(@"\iff", "⇔")]
        [InlineData(@"\Re", "ℜ")]
        [InlineData(@"\Im", "ℑ")]
        [InlineData(@"\odot", "⊙")]
        [InlineData(@"\approx", "≈")]
        [InlineData(@"\rightarrow", "→")]
        [InlineData(@"\leftarrow", "←")]
        [InlineData(@"\uparrow", "↑")]
        [InlineData(@"\downarrow", "↓")]
        [InlineData(@"\Rightarrow", "⇒")]
        [InlineData(@"\Leftarrow", "⇐")]
        [InlineData(@"\leftrightarrow", "↔")]
        [InlineData(@"\Leftrightarrow", "⇔")]
        [InlineData(@"The result is \approx 5.", "The result is ≈ 5.")]
        [InlineData(@"This \implies that and this \iff this.", "This ⇒ that and this ⇔ this.")]
        [InlineData(@"Move \rightarrow or \leftarrow.", "Move → or ←.")]
        [InlineData(@"An \uparrow and a \downarrow.", "An ↑ and a ↓.")]
        [InlineData(@"A \Rightarrow B \Leftarrow C.", "A ⇒ B ⇐ C.")]
        [InlineData(@"A \leftrightarrow B \Leftrightarrow C.", "A ↔ B ⇔ C.")]
        [InlineData(@"The vector is \perp to the plane.", "The vector is ⊥ to the plane.")]
        [InlineData(@"The lines are \parallel.", "The lines are ∥.")]
        [InlineData(@"This is a \odot operation.", "This is a ⊙ operation.")]
        [InlineData(@"The \Re part and the \Im part.", "The ℜ part and the ℑ part.")]
        public void ConvertToHumanFriendlyText_ConvertsCorrectly(string input, string expected)
        {
            var result = _converter.ConvertToHumanFriendlyText(input);
            Assert.Equal(expected, result);
        }

        [Theory]
        [InlineData(@"\textrm{k}", "k")]
        [InlineData(@"F_\textrm{k}", "F subscript k")]
        [InlineData(@"43^\circ", "43 degrees")]
        [InlineData(@"\alpha", "alpha")]
        [InlineData(@"\sqrt{x}", "the square root of x")]
        [InlineData(@"\frac{1}{2}", "fraction with numerator 1 and denominator 2")]
        [InlineData(@"a^{b+c}", "a to the power of b plus c")]
        [InlineData(@"x^{10}", "x to the power of 10")]
        [InlineData(@"x^{2}", "x squared")]
        [InlineData(@"\vec{v}", "vector v")]
        [InlineData(@"\hat{x}", "x hat")]
        [InlineData(@"\mathcal{E}_1", "calligraphic E subscript 1")]
        [InlineData(@"\mathbb{R}", "the set of real numbers")]
        [InlineData(@"\text{hello}", "hello")]
        [InlineData(@"\mathrm{N}", "N")]
        [InlineData(@"\vec{v}_0", "vector v subscript 0")]
        [InlineData(@"a^{b^{c}}", "a to the power of b to the power of c")]
        [InlineData(@"\frac{\sqrt{a^2+b^2}}{2}", "fraction with numerator the square root of a squared plus b squared and denominator 2")]
        [InlineData(@"\sum_{i=1}^{n} i^2", "summation from i equals 1 to n i squared")]
        [InlineData(@"\int_{0}^{\infty} e^{-x} dx", "integral from 0 to infinity e to the power of minus x dx")]
        [InlineData(@"\forall x \in \mathbb{R}", "for all x in the set of real numbers")]
        [InlineData(@"\bigg( \frac{a}{b} \bigg)", "fraction with numerator a and denominator b")]
        [InlineData(@"90^\circ", "90 degrees")]
        [InlineData(@"\(x_f\)", "x subscript f")]
        [InlineData(@"\(x_i = 0\)", "x subscript i equals 0")]
        [InlineData(@"\(k = 52\;\mathrm{N}/\mathrm{m}\).", "k equals 52 N divided by m.")]
        [InlineData(@"\(v\)", "v")]
        [InlineData("a\nb", "a\nb")]
        [InlineData("E = mc^2", "E equals mc squared")]
        [InlineData("4.0 \\times 10^{-4}", "4.0 times 10 to the power of minus 4")]
        [InlineData("sin^(-1)", "arcsin")]
        [InlineData("cos^(-1)", "arccos")]
        [InlineData("tan^(-1)", "arctan")]
        [InlineData("sqrt(x)", "the square root of x")]
        [InlineData("A small segment of the wire is marked in blue as \"d-x.\"", "A small segment of the wire is marked in blue as \"d-x.\"")]
        [InlineData("An x-y coordinate system is shown in the top right", "An x-y coordinate system is shown in the top right")]
        [InlineData("rod: dE_x = -k * lambda * x * dx / (a^2 + x^2)^(3/2).", "rod: dE subscript x equals minus k times lambda times x times dx divided by (a squared plus x squared) to the power of (3 divided by 2).")]
        [InlineData("V(r) = (q / (4 * \\pi * \\epsilon_0 * a_0)) * exp(-2 * r / a_0) * (1 + a_0/r).", "V(r) equals (q divided by (4 times pi times epsilon subscript 0 times a subscript 0)) times exp(minus 2 times r divided by a subscript 0) times (1 plus a subscript 0 divided by r).")]
        [InlineData(
            "sin^(-1) [ (lambda / (d * pi)) * cos^(-1) (sqrt(I / I_0)) ]", 
            "arcsin [ (lambda divided by (d times pi)) times arccos (the square root of I divided by I subscript 0) ]")]
        [InlineData("the quantity (x/2 squared plus l squared) raised to the 3/2 power", "the quantity (x divided by 2 squared plus l squared) raised to the 3 divided by 2 power")]
        [InlineData("y_ob to a", "y subscript ob to a")]
        [InlineData(@"\mu_k", "mu subscript k")]
        [InlineData(@"\geq", "greater than or equal to")]
        [InlineData("(-2)", "(minus 2)")]
        [InlineData("(a+b)", "(a plus b)")]
        [InlineData(@"a \pm b", "a plus-minus b")]
        [InlineData(@"a \neq b", "a not equal to b")]
        [InlineData(@"a \geq b", "a greater than or equal to b")]
        [InlineData(@"\forall x", "for all x")]
        [InlineData(@"\exists y", "exists y")]
        [InlineData(@"z \in S", "z in S")]
        [InlineData(@"\nabla f", "nabla f")]
        [InlineData(@"\partial f", "partial derivative f")]
        [InlineData(@"a \mp b", "a minus-plus b")]
        [InlineData(@"a \equiv b", "a equivalent to b")]
        [InlineData(@"\int_a^b f(x) dx", "integral from a to b f(x) dx")]
        [InlineData(@"\lim_{x \to \infty} f(x)", "limit as x approaches infinity of f(x)")]
        [InlineData(@"\begin{pmatrix} a & b \\ c & d \end{pmatrix}", "a 2x2 matrix with rows (a, b) and (c, d)")]
        [InlineData(@"\sin(x)", "sine of x")]
        [InlineData(@"\cos(x)", "cosine of x")]
        [InlineData(@"\tan(x)", "tangent of x")]
        [InlineData(@"\log(x)", "logarithm of x")]
        [InlineData(@"\ln(x)", "natural logarithm of x")]
        [InlineData(@"\exp(x)", "e to the power of x")]
        [InlineData(@"\det(A)", "determinant of A")]
        [InlineData(@"\binom{n}{k}", "n choose k")]
        [InlineData(@"\cup", "union")]
        [InlineData(@"\cap", "intersection")]
        [InlineData(@"\subset", "subset of")]
        [InlineData(@"\supset", "superset of")]
        [InlineData(@"\neg A", "not A")]
        [InlineData(@"A \land B", "A and B")]
        [InlineData(@"A \lor B", "A or B")]
        [InlineData(@"\hbar", "h-bar")]
        [InlineData(@"\ell", "ell")]
        [InlineData(@"\otimes", "tensor product")]
        [InlineData(@"\parallel", "parallel to")]
        [InlineData(@"\perp", "perpendicular to")]
        [InlineData(@"\implies", "implies")]
        [InlineData(@"\iff", "if and only if")]
        [InlineData(@"\Re", "Real part")]
        [InlineData(@"\Im", "Imaginary part")]
        [InlineData(@"\odot", "circled dot")]
        [InlineData(@"\approx", "approximately equal to")]
        [InlineData(@"\rightarrow", "right arrow")]
        [InlineData(@"\leftarrow", "left arrow")]
        [InlineData(@"\uparrow", "up arrow")]
        [InlineData(@"\downarrow", "down arrow")]
        [InlineData(@"\Rightarrow", "rightwards double arrow")]
        [InlineData(@"\Leftarrow", "leftwards double arrow")]
        [InlineData(@"\leftrightarrow", "left right arrow")]
        [InlineData(@"\Leftrightarrow", "left right double arrow")]
        [InlineData(@"The result is \approx 5.", "The result is approximately equal to 5.")]
        [InlineData(@"This \implies that and this \iff this.", "This implies that and this if and only if this.")]
        [InlineData(@"Move \rightarrow or \leftarrow.", "Move right arrow or left arrow.")]
        [InlineData(@"An \uparrow and a \downarrow.", "An up arrow and a down arrow.")]
        [InlineData(@"A \Rightarrow B \Leftarrow C.", "A rightwards double arrow B leftwards double arrow C.")]
        [InlineData(@"A \leftrightarrow B \Leftrightarrow C.", "A left right arrow B left right double arrow C.")]
        [InlineData(@"The vector is \perp to the plane.", "The vector is perpendicular to to the plane.")]
        [InlineData(@"The lines are \parallel.", "The lines are parallel to.")]
        [InlineData(@"This is a \odot operation.", "This is a circled dot operation.")]
        [InlineData(@"The \Re part and the \Im part.", "The Real part part and the Imaginary part part.")]
        public void ConvertToScreenReaderFriendlyText_ConvertsCorrectly(string input, string expected)
        {
            var result = _converter.ConvertToScreenReaderFriendlyText(input);
            Assert.Equal(expected, result);
        }
    }
}